apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  index.html.0: |
    <html>
      <head><title>pod 0</title></head>
      <body>
        index page for pod 0
      </body>
    </html>
  index.html.1: |
    <html>
      <head><title>pod 1</title></head>
      <body>
        index page for pod 1
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-0
  name: nginx-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-0
  template:
    metadata:
      labels:
        app: nginx-0
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html.0
      volumes:
      - name: index
        configMap:
          name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-1
  name: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html.1
      volumes:
      - name: index
        configMap:
          name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-0
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30000
    port: 80
    targetPort: http
  selector:
    app: nginx-0
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30001
    port: 80
    targetPort: http
  selector:
    app: nginx-1
